"""add new column for product

Revision ID: 112daa05720e
Revises: bdfdf47e4489
Create Date: 2024-09-24 23:30:16.495634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112daa05720e'
down_revision: Union[str, None] = 'bdfdf47e4489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available_quantity')
    # ### end Alembic commands ###
